---
# NOTE(shadower): the AWS playbook builds an in-memory inventory of
# all the EC2 instances here. We don't need to as that's done by the
# dynamic inventory.

# TODO(shadower): the AWS playbook sets the
# `openshift_master_cluster_hostname` and `osm_custom_cors_origins`
# values here. We do it in the OSEv3 group vars. Do we need to add
# some logic here?

- import_playbook: ../../prerequisites.yml

- name: Prepare the Nodes in the cluster for installation
  any_errors_fatal: true
  hosts: new_nodes
  become: yes
  gather_facts: yes
  tasks:
  - name: Install dependencies
    import_role:
      name: openshift_openstack
      tasks_from: node-packages.yml

  - name: Configure Node
    import_role:
      name: openshift_openstack
      tasks_from: node-configuration.yml
