---
- name: Generate the templates
  include_tasks: generate-templates.yml
  when:
  - openshift_openstack_stack_state == 'present'

- name: Handle the Stack (create/delete)
  ignore_errors: False
  register: stack_create
  os_stack:
    name: "{{ openshift_openstack_stack_name }}"
    state: "{{ openshift_openstack_stack_state }}"
    template: "{{ stack_template_path | default(omit) }}"
    wait: yes

- name: Add the new nodes to the inventory
  meta: refresh_inventory

- name: Legacy LBaaSv2 SG OpenShift API correction
  os_port:
    state: present
    name: "{{ openshift_openstack_api_lb_port_id }}"
    security_groups:
    - "{{ openshift_openstack_api_lb_sg_id }}"
  when:
  - openshift_openstack_api_lb_provider == "haproxy"

- name: CleanUp
  include_tasks: cleanup.yml
  when:
  - openshift_openstack_stack_state == 'present'

# TODO(shadower): create the registry and PV Cinder volumes if specified
# and include the `prepare-and-format-cinder-volume` tasks to set it up
